= Java oefeningen
:icons: font
:source-language: java
:source-highlighter: pygments
:pygments-style: friendly

== Arrays

=== Inleidende oefening

Maak een klasse `ArrayOefeningen` aan, die de volgende `main` methode bevat.

[source]
----
public class ArrayOefeningen {

	// Zelf aanvullen...

	public static void main(String[] args) {
		double[] cijfers = new double[] {
				24.0, 21.0, 1.0, 4.0, 32.0, 12.0, 15.0, 8.0 };

		System.out.println("Minimum: " + min(cijfers));
		System.out.println("Maximum: " + max(cijfers));
		System.out.println("Gemiddelde: " + gemiddelde(cijfers));

		// Verder aanvullen...
	}
}
----

Schrijf de verwachte *statische* methodes, die enkele statistieken van een array weergeven.

[NOTE]
====
Een statische methode wordt gedefinieerd met het keyword `static`, bijvoorbeeld

[source]
----
private static int max(int a, int b);
----

====

- De kleinste en grootste waarde uit de array: `min` en `max`.
- Het gemiddelde: `gemiddelde`.

De verwachte output is de volgende:

----
Minimum: 1.0
Maximum: 32.0
Gemiddelde: 14.625
----

Schrijf de statische methode `deelSommen`. Deze neemt twee argumenten, namelijk de array waarop de deelsommen worden berekend, en een geheel getal `n`, dat voorstelt uit hoeveel getallen een deelsom wordt opgebouwd. Deze methode splitst de originale array op in gelijke delen van grootte `n`, en berekent hiervan telkens de som. Het resultaat bestaat uit een array van deze deelsommen.

Vul de `main` methode verder aan, zodat de deelsommen voor `n = {1, 2, 4}` worden weergegeven.

----
Deelsommen voor n=1: 117.0
Deelsommen voor n=2: 50.0, 67.0
Deelsommen voor n=4: 45.0, 5.0, 44.0, 23.0
----

=== Verdere oefeningen

In een nieuw project, maak de klasse `VerdereOefeningen` aan, met daarin een `main` methode. Elke oefening binnen dit onderdeel dien je te implementeren als statische methode binnen deze klasse (eventueel aangevuld met eigen hulpmethodes).

==== Energierekening

Het verbruik (in kW) van een hele dag wordt in een array opgeslaan, waarbij elk element het verbruik van een bepaald uur van de dag voorstelt (het element op positie 0 staat voor het verbruik van 0u tot 1u, het element op positie 1 voor het verbruik van 1u tot 2u, etc.).

Schrijf de methode `berekenPrijs`, die de energieprijs voor een gegeven dag berekent. Deze methode heeft drie argumenten, namelijk een array die het verbruik van een dag voorstelt, een _double_, die het dagtarief per uur voorstelt, en een _double_ die het nachttarief per uur voorstelt. Het nachttarief wordt toegepast van 22u tot 6u.

Test deze methode uit in je `main` methode.

[source]
----
double[] dagVerbruik = new double[] { 8.8, 2.43, 7.67, 9.87, 7.08, 3.44, 6.98, 4.9, 7.54, 2.27, 8.77, 8.12, 2.73, 2.52, 7.45, 2.05, 8.85, 6.3, 4.69, 5.96, 3.53, 6.85, 3.63, 9.77 };

System.out.println("Prijs: " + berekenPrijs(dagVerbruik, 11.0, 4.0)); // Prijs: 1195.37
----

In een productiebedrijf hangen twee monitoren. De eerste monitor meet het cumulatieve verbruik, terwijl de tweede het aantal pieken telt.

Schrijf de methode `monitorVerbruik`. Deze heeft twee argumenten, namelijk een array die het verbruik van de dag weergeeft, en een _double_ die een grens voorstelt. Het resultaat van deze methode is het uur waarna het totale verbruik van die dag de grens overschreidt. Indien de grens nooit wordt overschreden, geeft deze methode `-1` terug.

[source]
----
System.out.println(monitorVerbruik(dagVerbruik, 20.0))    // 3
System.out.println(monitorVerbruik(dagVerbruik, 100.0))   // 16
System.out.println(monitorVerbruik(dagVerbruik, 10000.0)) // -1
----

Schrijf de methode `monitorPiek`. Analoog aan de vorige methode heeft deze twee argumenten. Ditmaal stelt het tweede argument een piekgrens voor. Het resultaat van deze methode is het aantal uren waarbij het verbruik hoger was dan deze piekgrens.

[source]
----
System.out.println(monitorPiek(dagVerbruik, 7.0)) // 10
System.out.println(monitorPiek(dagVerbruik, 9.0)) // 2
----

==== Volgorde controleren

Schrijf de methode `isGesorteerd`. Deze methode heeft twee argumenten, namelijk de array die we wensen te controleren, een een _boolean_ `oplopend`. Deze methode gaat na of een array oplopend, dan wel aflopend, is gesorteerd.

[source]
----
double[] a = new double[] { 41.09, 4.94, 18.77, 41.84, 5.6, 49.49, 61.57, 74.91, 17.47, 13.82 };
double[] b = new double[] { 4.94, 5.6, 13.82, 17.47, 18.77, 41.09, 41.84, 49.49, 61.57, 74.91 };
double[] c = new double[] { 74.91, 61.57, 49.49, 41.84, 41.09, 18.77, 17.47, 13.82, 5.6, 4.94 };

System.out.println(isGesorteerd(a, true));  // false
System.out.println(isGesorteerd(a, false)); // false

System.out.println(isGesorteerd(b, true));  // true
System.out.println(isGesorteerd(b, false)); // false

System.out.println(isGesorteerd(c, false)); // true
----

==== Aantallen

Schrijf de methode `countMulti`. Deze methode heeft twee argumenten, namelijk de _integer_ array waarin we gaan tellen, en een tweede array van waarden die we willen tellen. Deze methode geeft terug hoe vaak deze waarden voorkomen in de eerste array.

[TIP]
====
Los deze oefening op aan de hand van een ingebouwde methode.
====

[source]
----
int[] waarden = new int[] { 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5 };

System.out.println(countMulti(waarden, new int[] { 1, 5 }));    // 4
System.out.println(countMulti(waarden, new int[] { 2, 3, 4 })); // 13
----

==== Palindroom

Een array is een palindroom wanneer het dezelfde getallen bevat van voor naar achter, als van achter naar voor (analoog aan het woord "lepel"). Schrijf de methode `isPalindroom` die voor een array van _integers_ nagaat of deze een palindroom is.

[source]
----
System.out.println(isPalindroom(new int[] { 1, 2, 3, 4 }));    // false
System.out.println(isPalindroom(new int[] { 1, 2, 2, 1 }));    // true
System.out.println(isPalindroom(new int[] { 7, 5, 6, 5, 7 })); // true
----

==== Driehoeken

Schrijf de methode `soortDriehoek`. Deze heeft één argument, namelijk een array van _integers_. Deze zal steeds drie elementen bevatten, die de hoeken van een driehoek voorstellen. De methode geeft een geheel getal terug, dat voorstelt om welk type driehoek het gaat.

|===
| Type | Waarde

| Ongeldige driehoek | -1
| Gelijkzijdige driehoek | 2
| Gelijkbenige driehoek | 1
| Willekeurige driehoek | 0
|===

[source]
----
System.out.println(soortDriehoek(new int[] { 100, 10, 30 })); // -1
System.out.println(soortDriehoek(new int[] { 235, 14, 92 })); // -1
System.out.println(soortDriehoek(new int[] { 60, 60, 60 }));  // 2
System.out.println(soortDriehoek(new int[] { 80, 80, 20 }));  // 1
System.out.println(soortDriehoek(new int[] { 50, 60, 70 }));  // 0
----

=== Een eigen containerklasse

De Java-bibliotheek bevat standaard enkele containers. Eén daarvan is `ArrayList`, die een lijst met variabele lengte implementeert. In deze oefening schrijven we onze eigen implementatie voor deze container.

[NOTE]
====
De containertypes binnen de Java-bibliotheek zijn *generiek* geprogrammeerd, waardoor ze werken met alle types. Zo kan je een lijst van _integers_ initialiseren met `ArrayList<int>`. Analoog wordt een lijst van _doubles_ aangemaakt via `ArrayList<double>`. Bij onze eigen implementatie beperken we ons echter tot een containerklasse die _integers_ kan opslaan.
====

Start een nieuw project, met daarin de volgende klassen (in het default package):

- De klasse `Main`. Deze zal uitsluitend de `main` methode bevatten.
- De klasse `IntLijst`. Deze zal de implementatie bevatten van onze lijstklasse.

[NOTE]
====
Hoewel wordt afgeraden om klassen rechtstreeks te definiëren in het default package, zullen we dit in deze oefeningen toch doen, om zo consequent te zijn met de cursus. Dit laat eveneens toe om de volledige broncode te kopiëren en plakken in Dodona.
====

Implementeer voor de klasse `IntLijst` de volgende methodes, en test deze zelf *kritisch* uit in de `main` methode:

1. Een default constructor. Deze initialiseert een lege lijst.
2. Een niet-default constructor, die als argument een array van _integers_ heeft. Aan de hand van deze array wordt de lijst geïnitialiseerd.
3. De methode `voegToe`. Deze heeft een _integer_ als argument, en voegt deze achteraan de lijst toe.
4. De methode `verwijder`, met een _integer_ als argument. Indien dit getal voorkomt in de lijst, dan verwijdert deze methode het eerste voorkomen van dit getal.
+
[WARNING]
====
Naast een oefening op arrays, is dit vooral een denkoefening. Alvorens je echt aan het coderen gaat, stel je best een mentale roadmap op. Bedenk hoe je binnen jouw lijstimplementatie een reeks getallen zal opslaan. Logische bewerkingen op deze lijst zijn een getal toevoegen en een getal verwijderen. Een naïeve manier om dit te implementeren zou de volgende kunnen zijn:

- Begin met een lege array van _integers_.
- Bij elke toevoeging, maak een nieuwe array die exact één element meer bevat dan de originele; kopieer vervolgens alle elementen uit de originele array naar de nieuwe, en plaats het toe te voegen element achteraan deze nieuwe array.
- De verwijdering loopt analoog aan de toevoeging, behalve dat je nu een array maakt die één element minder bevat dan de originele. Deze nieuwe array zal alle elementen uit de oude array bevatten, op het te verwijderen element na.

Aangezien een array aanmaken, en vooral het kopiëren van alle getallen een dure operatie is, is deze manier van werken zeker niet de meest optimale. Als pure programmeeroefening kan je de methode `voegToe` en `verwijder` eerst op deze manier implementeren, maar nadien is het aangeraden om deze op een andere, meer efficiente manier te implementeren. Bedenk zelf hoe je dit zou doen.
====
+
5. De methode `maakLeeg` maakt de volledige lijst leeg.
6. De methode `verwijderAlle` heeft een _integer_ als argument, en verwijdert alle voorkomens van dit getal uit de lijst.
7. De methode `reverse` draait de lijst om.
