= Java oefeningen
:icons: font
:source-language: java
:source-highlighter: pygments
:pygments-style: friendly

== Arrays

=== Inleidende oefening

Maak een klasse `ArrayOefeningen` aan, die de volgende `main` methode bevat.

[source]
----
public class ArrayOefeningen {

	// Zelf aanvullen...

	public static void main(String[] args) {
		double[] cijfers = new double[] {
				24.0, 21.0, 1.0, 4.0, 32.0, 12.0, 15.0, 8.0 };

		System.out.println("Minimum: " + min(cijfers));
		System.out.println("Maximum: " + max(cijfers));
		System.out.println("Gemiddelde: " + gemiddelde(cijfers));

		// Verder aanvullen...
	}
}
----

Schrijf de verwachte *statische* methodes, die enkele statistieken van een array weergeven.

[NOTE]
====
Een statische methode wordt gedefinieerd met het keyword `static`, bijvoorbeeld

[source]
----
private static int max(int a, int b);
----

====

- De kleinste en grootste waarde uit de array: `min` en `max`.
- Het gemiddelde: `gemiddelde`.

De verwachte output is de volgende:

----
Minimum: 1.0
Maximum: 32.0
Gemiddelde: 14.625
----

Schrijf de statische methode `deelSommen`. Deze neemt twee argumenten, namelijk de array waarop de deelsommen worden berekend, en een geheel getal `n`, dat voorstelt uit hoeveel getallen een deelsom wordt opgebouwd. Deze methode splitst de originale array op in gelijke delen van grootte `n`, en berekent hiervan telkens de som. Het resultaat bestaat uit een array van deze deelsommen.

Vul de `main` methode verder aan, zodat de deelsommen voor `n = {1, 2, 4}` worden weergegeven.

----
Deelsommen voor n=1: 117.0
Deelsommen voor n=2: 50.0, 67.0
Deelsommen voor n=4: 45.0, 5.0, 44.0, 23.0
----

Schrijf de statische methode `filterEven`. Deze neemt als enige argument de array waaruit we de even getallen wensen te filteren. Het resultaat is een nieuwe array, die enkel de even getallen uit de originele array bevat.

----
Even getallen: 24.0, 4.0, 32.0, 12.0, 8.0
----

Schrijf, analoog aan de methode `filterEven`, de methode `filterMetGrens`. Deze neemt drie argumenten, namelijk

1. de array waaruit we wensen te filteren,
2. de grens, die ofwel een bovengrens, ofwel een ondergrens zal zijn, afhankelijk van,
3. een _boolean_ `isOnderGrens`, die aangeeft of de grens al dan niet een ondergrens is.

Deze methode geeft een nieuwe array terug, die de getallen onder (of boven) de grens bevat, exclusief de grens. Gebruik *uitsluitend* deze methode om de volgende output toe te voegen aan je `main` methode:

----
Getallen groter dan 20.0: 24.0, 32.0
Getallen kleiner dan 10.0: 1.0, 4.0, 8.0
Getallen tussen 8.0 (exclusief) en 18.0 (exclusief): 12.0, 15.0
----

=== Een eigen containerklasse

De Java-bibliotheek bevat standaard enkele containers. Eén daarvan is `ArrayList`, die een lijst met variabele lengte implementeert. In deze oefening schrijven we onze eigen implementatie voor deze container.

[NOTE]
====
De containertypes binnen de Java-bibliotheek zijn *generiek* geprogrammeerd, waardoor ze werken met alle types. Zo kan je een lijst van _integers_ initialiseren met `ArrayList<int>`. Analoog wordt een lijst van _doubles_ aangemaakt via `ArrayList<double>`. Bij onze eigen implementatie beperken we ons echter tot een containerklasse die _integers_ kan opslaan.
====

Start een nieuw project, met daarin de volgende klassen (in het default package):

- De klasse `Main`. Deze zal uitsluitend de `main` methode bevatten.
- De klasse `IntLijst`. Deze zal de implementatie bevatten van onze lijstklasse.

[NOTE]
====
Hoewel wordt afgeraden om klassen rechtstreeks te definiëren in het default package, zullen we dit in deze oefeningen toch doen, om zo consequent te zijn met de cursus. Dit laat eveneens toe om de volledige broncode te kopiëren en plakken in Dodona.
====

Implementeer voor de klasse `IntLijst` de volgende methodes, en test deze zelf *kritisch* uit in de `main` methode:

1. Een default constructor. Deze initialiseert een lege lijst.
2. Een niet-default constructor, die als argument een array van _integers_ heeft. Aan de hand van deze array wordt de lijst geïnitialiseerd.
3. De methode `voegToe`. Deze heeft een _integer_ als argument, en voegt deze achteraan de lijst toe.
4. De methode `verwijder`, met een _integer_ als argument. Indien dit getal voorkomt in de lijst, dan verwijdert deze methode het eerste voorkomen van dit getal.
+
[WARNING]
====
Naast een oefening op arrays, is dit vooral een denkoefening. Alvorens je echt aan het coderen gaat, stel je best een mentale roadmap op. Bedenk hoe je binnen jouw lijstimplementatie een reeks getallen zal opslaan. Logische bewerkingen op deze lijst zijn een getal toevoegen en een getal verwijderen. Een naïeve manier om dit te implementeren zou de volgende kunnen zijn:

- Begin met een lege array van _integers_.
- Bij elke toevoeging, maak een nieuwe array die exact één element meer bevat dan de originele; kopieer vervolgens alle elementen uit de originele array naar de nieuwe, en plaats het toe te voegen element achteraan deze nieuwe array.
- De verwijdering loopt analoog aan de toevoeging, behalve dat je nu een array maakt die één element minder bevat dan de originele. Deze nieuwe array zal alle elementen uit de oude array bevatten, op het te verwijderen element na.

Aangezien een array aanmaken, en vooral het kopiëren van alle getallen een dure operatie is, is deze manier van werken zeker niet de meest optimale. Als pure programmeeroefening kan je de methode `voegToe` en `verwijder` eerst op deze manier implementeren, maar nadien is het aangeraden om deze op een andere, meer efficiente manier te implementeren. Bedenk zelf hoe je dit zou doen.
====
+
5. De methode `maakLeeg` maakt de volledige lijst leeg.
6. De methode `verwijderAlle` heeft een _integer_ als argument, en verwijdert alle voorkomens van dit getal uit de lijst.
7. De methode `reverse` draait de lijst om.
